global:
  domain: eu2.coralogix.com
  clusterName: hellas-poc  # replace with your cluster name
opentelemetry-cluster-collector:
  presets:
    kubernetesEvents:
      enabled: true
    reduceResourceAttributes:
      enabled: true
    kubernetesResources:
      enabled: true
    fleetManagement:
      enabled: true
      supervisor:
        enabled: true
    clusterMetrics:
      enabled: true
    collectorMetrics:
      enabled: true
    kubernetesApiServerMetrics:
      enabled: true
      scrapeAll: false
  distribution: eks
  provider: aws
opentelemetry-agent:
  presets:
    hostEntityEvents:
      enabled: true
    fleetManagement:
      enabled: true
      supervisor:
        enabled: true
    spanMetrics:
      enabled: true
      histogramBuckets:
      - 1ms
      - 4ms
      - 10ms
      - 20ms
      - 50ms
      - 100ms
      - 200ms
      - 500ms
      - 1s
      - 2s
      - 5s
      transformStatements: []
    loadBalancing:
      routingKey: traceID
      enabled: true
      hostname: coralogix-opentelemetry-gateway
    coralogixExporter:
      enabled: true
      pipelines:
      - logs
      - metrics
      - profiles
      privateKey: ${env:CORALOGIX_PRIVATE_KEY}
    profilesCollection:
      enabled: true
    transactions:
      enabled: false
    logsCollection:
      enabled: true
      reduceLogAttributes:
        enabled: true
    kubeletMetrics:
      enabled: true
    collectorMetrics:
      enabled: true
    statsdReceiver:
      enabled: true
    hostMetrics:
      enabled: true
      process:
        enabled: true
    kubernetesExtraMetrics:
      enabled: true
      scrapeAll: false
      perNode: true
    reduceResourceAttributes:
      enabled: true
  config:
    service:
      pipelines:
        traces:
          exporters:
          - loadbalancing
  targetAllocator:
    enabled: false
  command:
    extraArgs:
      - --feature-gates=service.profilesSupport
  distribution: eks
  provider: aws
opentelemetry-gateway:
  config:
    processors:
      tail_sampling:
        policies:
        - name: errors
          type: status_code
          status_code:
            status_codes:
            - ERROR
        - name: randomized-10-percent
          type: probabilistic
          probabilistic:
            sampling_percentage: 10
        decision_wait: 30
  replicaCount: 3
  enabled: true
  presets:
    collectorMetrics:
      enabled: true
    fleetManagement:
      enabled: true
      supervisor:
        enabled: true
  distribution: eks
  provider: aws
coralogix-ebpf-profiler:
  enabled: false
opentelemetry-ebpf-instrumentation:
  enabled: true  # eBPF auto-instrumentation — confirm with George
coralogix-operator:
  enabled: false
